import {styleTags, tags as t} from "@lezer/highlight"

export const cueHighlighting = styleTags({
  "import package": t.moduleKeyword,
  Literal: t.literal,
  "SimpleStringLit SimpleBytesLit MultilineStringLit MultilineBytesLit AttributeString ImportPath": t.string,
  Escape: t.escape,
  Interpolation: [],
  "InterpolationStart InterpolationEnd": t.special(t.brace),
  "IntLit/...": t.number,
  "BoolLit/...": t.bool,
  FloatLit: t.float,
  null: t.null,
  "OperandName/Identifier": t.variableName,
  "LabelName/Identifier": t.propertyName,
  Comment: t.comment,
  "&& ||": t.logicOperator,
  // "+ - * /": t.arithmeticOperator,
  "| &": t.bitwiseOperator,
  // "== != < <= > >= =~ !~": t.compareOperator,
  ",": t.separator,
  "Ellipsis/... :": t.punctuation,
  "( )": t.paren,
  "[ ]": t.squareBracket,
  "{ }": t.brace,
})
