import {styleTags, tags as t} from "@lezer/highlight"

export const cueHighlighting = styleTags({
  "import package": t.moduleKeyword,
  "for if try else fallback otherwise": t.controlKeyword,
  let: t.definitionKeyword,
  in: t.operatorKeyword,

  "LabelName/Identifier! Selector/Identifier!": t.propertyName,
  "LabelName/SimpleStringLit Selector/SimpleStringLit": t.propertyName,
  "ForClause/Identifier! TryClause/Identifier! LetClause/Identifier! AliasExpr/Identifier! Label/Identifier! PostfixAlias/Identifier!": t.definition(t.variableName),
  "PackageName/Identifier!": t.definition(t.namespace),
  "OperandName/Identifier!": t.variableName,
  "Attribute/Identifier!": t.attributeName,

  Literal: t.literal,
  "SimpleStringLit SimpleBytesLit MultilineStringLit MultilineBytesLit AttributeString ImportPath": t.string,
  Escape: t.escape,
  Interpolation: [],
  "InterpolationStart InterpolationEnd": t.special(t.brace),
  "IntLit/...": t.integer,
  "BoolLit/...": t.bool,
  FloatLit: t.float,
  "NullLit/...": t.null,
  "BottomLit Top": t.atom,
  Comment: t.comment,

  "&& ||": t.logicOperator,
  "+ -": t.arithmeticOperator,
  '"*" "/"': t.arithmeticOperator,
  "| &": t.bitwiseOperator,
  '== "!=" < <= > >= =~ "!~"': t.compareOperator,
  '"!"': t.logicOperator,
  "= ~": t.definitionOperator,
  ".": t.derefOperator,
  ",": t.separator,
  ":": t.punctuation,
  '"..."': t.punctuation,
  "? @": t.punctuation,
  'LabelExpr/"!" Label/"!"': t.punctuation,
  "( )": t.paren,
  "[ ]": t.squareBracket,
  "{ }": t.brace,
})
